name: Test

on:
  push:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Get repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23"

      - name: Install packages
        run: go install

      - name: Run tests
        run: make test
